/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniInvoker */

#ifndef _Included_JniInvoker
#define _Included_JniInvoker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniInvoker
 * Method:    getStringFromCPP
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JniInvoker_getStringFromCPP
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
